innovationLabs/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
]

innovationLabs/dashboard/urls.py
from django.urls import path
from .views import NoticiaListView, NoticiaCreate, NoticiaUpdate, NoticiaDelete 
from .views import EspecializacionListView, EspecializacionCreate, EspecializacionUpdate
from .views import EspecializacionDelete, RecursoCreate, RecursoListView, RecursoDelete, RecursoUpdate
from .views import ColaboradorListView, ColaboradorCreate, ColaboradorUpdate, ColaboradorDelete 
from . import views

app_name = "dashboard"

urlpatterns = [
	path('', views.dashboard, name="dashboard"),

	path('noticias-publicadas/', NoticiaListView.as_view(), name="publicadas"),
	path('nueva-noticia/', NoticiaCreate.as_view(), name="nueva"),
	path('editar-noticia/<int:pk>/', NoticiaUpdate.as_view(), name="editar"),
	path('borrar-noticia/<int:pk>/', NoticiaDelete.as_view(), name="borrar"),

	path('especializaciones-publicadas/', EspecializacionListView.as_view(), name="especializaciones-publicadas"),
	path('nueva-especializacion/', EspecializacionCreate.as_view(), name="nueva-especializacion"),
	path('editar-especializacion/<int:pk>/', EspecializacionUpdate.as_view(), name="editar-especializacion"),
	path('borrar-especializacion/<int:pk>/', EspecializacionDelete.as_view(), name="borrar-especializacion"),

	path('nuevo-recurso/', RecursoCreate.as_view(), name="nuevo-recurso"),
	path('recursos-publicados/', RecursoListView.as_view(), name="recursos-publicados"),
	path('borrar-recurso/<int:pk>/', RecursoDelete.as_view(), name="borrar-recurso"),
	path('editar-recurso/<int:pk>/', RecursoUpdate.as_view(), name="editar-recurso"),

	path('nuevo-colaborador/', ColaboradorCreate.as_view(), name="nuevo-colaborador"),
	path('colaboradores-publicados/', ColaboradorListView.as_view(), name="colaboradores-publicados"),
	path('borrar-colaborador/<int:pk>/', ColaboradorDelete.as_view(), name="borrar-colaborador"),
	path('editar-colaborador/<int:pk>/', ColaboradorUpdate.as_view(), name="editar-colaborador")

]

innovationLabs/innovationLabs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'core.views.page_not_found'

urlpatterns = [
	# paths del core
	path('', include('core.urls')),
    # paths de noticias
    path('noticias/', include('noticias.urls')),
    # paths de especializacion
    path('especializacion/', include('especializacion.urls')),
    # paths de normativa
    path('normativas/', include('normativa.urls')),
    # paths de laboratorios
    path('laboratorios/', include('laboratorios.urls')),
    # paths de recursos
    path('recursos/', include('recursos.urls')),
    # paths de colaboradores
    path('colaboradores/', include('colaboradores.urls')),
    # paths de login
    path('accounts/', include('django.contrib.auth.urls')),
    # paths de dashboard
    path('dashboard/', include('dashboard.urls')),
	# paths del admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovationLabs/noticias/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.noticias, name="noticias"),
	path('noticia/<int:noticia_id>/<slug:noticia_slug>/', views.noticia, name="noticia"),
]

innovationLabs/noticias/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from stdimage import StdImageField, validators
# from stdimage.validators import MinSizeValidator, MaxSizeValidator

class Noticia(models.Model):
    destacada = models.BooleanField(default=False)
    laboratorio = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    nombre_laboratorio = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(verbose_name="titulo", max_length=200)
    content = RichTextField(verbose_name="contenido")
    # image = StdImageField(upload_to = "noticias", verbose_name="imagen", blank=True, null=True, variations={'thumbnail': (960, 540)}, validators=[MinSizeValidator(960, 540)])
    image = StdImageField(upload_to = "noticias", verbose_name="imagen", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")


    class Meta:
        verbose_name = "noticia"
        verbose_name_plural = "noticias"
        ordering = ['created']

    def __str__(self):
        return self.title

innovationLabs/noticias/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import Group, User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Noticia
from normativa.models import Normativa

def noticias(request):
	noticias = Noticia.objects.all().order_by('-created')[:45]
	paginator = Paginator(noticias, 9)
	page = request.GET.get('page')

	normativas = Normativa.objects.all().order_by('created')

	try:
		noticias = paginator.page(page)
	except PageNotAnInteger:
		noticias = paginator.page(1)
	except EmptyPage:
		noticias = paginator.page(paginator.num_pages)
	return render(request, "noticias/noticias.html", {'noticias': noticias, 'normativas':normativas})

def noticia(request, noticia_id, noticia_slug):
	noticia = get_object_or_404(Noticia, id=noticia_id)
	noticias_recientes = Noticia.objects.exclude(id=noticia_id).order_by('-id')[:4]
	normativas = Normativa.objects.all().order_by('created')

	try:
		querry_group=Group.objects.filter(user=noticia.laboratorio_id)
	except:
		querry_group=None

	return render(request, "noticias/noticia.html", {
		'noticia': noticia, 
		'noticias_recientes': noticias_recientes, 
		'groups': querry_group, 
		'normativas':normativas
	})

innovationLabs/noticias/templates/noticias/noticia.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <main class="col-lg-8">
      <div class="blog-post">
        <h2 class="blog-post-title">{{noticia.title}}</h2>
        <p class="blog-post-meta text-left">{{noticia.created | date:"SHORT_DATE_FORMAT"}}
        {% if noticia.laboratorio %}
          - Redactado por
          <strong>{{noticia.laboratorio.first_name}} {{noticia.laboratorio.last_name}}</strong>
          colaborador de 
          {% for group in groups %}
            <strong>{{group}}</strong></p>
          {% endfor %}
        {% endif %}

        {% if noticia.image.url != None %}
          <img class="mt-3" src="{{noticia.image.url}}" loading="lazy" width="100%" height="100%">
          <hr class="mt-5">
        {% endif %}
        {{noticia.content|safe}}
      </div>

      <a type="button" class="btn btn-outline-primary float-left mt-4" href="{% url 'noticias' %}" >
        <i class="fas fa-arrow-left"></i> Regresar
      </a>
    </main>

    <aside class="col-lg-4 col-sm-12 mt-5">
      <h4 class="mt-5 mb-4">Noticias recientes</h4>
        <div>
        {% for noticia in noticias_recientes %}
          <a href="{% url 'noticia' noticia.id noticia.title|slugify %}">
            <div class="card border-primary mb-2 p-0">
              <div class="row no-gutters">
                <div class="col-6">
                  <img src="{{noticia.image.url}}" class="img-fluid" alt="...">
                </div>
                <div class="col-6">
                  <div class="px-2">
                    <small style="color: black;">{{noticia.title}}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
        {% endfor %}
      </div>
    </aside>
  </div>
  
</div>
{% endblock %}

innovationLabs/noticias/templates/noticias/noticia_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}

{% load static %}

{% block content %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form action="" method="post">{% csrf_token %}
              <h3>¿Estás seguro de que quieres borrar la noticia <strong>{{ object.title }}</strong>?</h3>
              <input class="btn btn-danger" type="submit" value="Sí, borrar la noticia"/>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

innovationLabs/noticias/templates/noticias/noticia_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}
<br>
<div class="col-12">
  
  {% if 'ok' in request.GET %}
  <div class="alert alert-success" role="alert">
    Noticia actualizada correctamente
  </div>
  {% endif %}

  <form method="post" enctype="multipart/form-data">{% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="Guardar">
  </form>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

innovationLabs/noticias/templates/noticias/noticia_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

<main role="main">
  <div class="container">
  
    <a class="btn btn-success float-right" href="{% url 'dashboard:nueva' %}">
      <i class="fas fa-plus"></i> Nueva Noticia
    </a>

    <br><br>

    {% for noticia in noticia_list %}
      <h4 class="mb-2">{{noticia.title}}</h4>
      {% if noticia.image.url != None %}
        <img src="{{noticia.image.url}}" width="192" height="108" class="mb-2">
      {% endif %}
      <p>{{noticia.content|striptags|safe|truncatechars:"300"}}</p>
      <a class="btn btn-warning btn-sm" href="{% url 'dashboard:editar' noticia.id %}">
        <i class="fas fa-edit"></i> Editar</a>
      <a class="btn btn-danger btn-sm" href="{% url 'dashboard:borrar' noticia.id %}">
        <i class="fas fa-trash"></i> Borrar</a>
      <hr>
    {% endfor %}
  </div>

  <!-- Menú de paginación -->
  {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&laquo;</a>
          </li>
        {% endif %}
        {% for i in paginator.page_range %}
          <li class="page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
</main>
{% endblock %}

innovationLabs/noticias/templates/noticias/noticias.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <div class="col-12">
      <div class="text-center">
        <h1 class="text-center">Noticias</h1>
        <hr class="pb-5">
      </div>
    </div>
  </div>
	
  <div class="row">
		{% for noticia in noticias %}
		<div class="col-lg-4 col-md-6 col-sm-12">
			<div class="card text-dark border-primary mb-4">
			  	{% if noticia.image.url != None %}
				<a href="{% url 'noticia' noticia.id noticia.title|slugify %}">
					<img src="{{noticia.image.url}}" loading="lazy" class="img-fluid" alt="...">
				</a>
				{% endif %}
			  	<div class="card-body">
					<a href="{% url 'noticia' noticia.id noticia.title|slugify %}" class="card-title" 
					   style="color: black; font-weight: bold;" >
						{{noticia.title}}
					</a>
					
					<hr>
					<p class="card-text text-justify">{{noticia.content|striptags|safe|truncatechars:"200"}}</p>
					<p class="float-left">{{noticia.created | date:"SHORT_DATE_FORMAT"}}</p>
					<a href="{% url 'noticia' noticia.id noticia.title|slugify %}" class="float-right">Leer más</a>
			  </div>
			</div>
		</div>
		{% endfor %}

		<div class="col-12">
			<!-- Menú de paginación -->
			{% if noticias.has_next or noticias.has_previous %}
			<nav aria-label="Page navigation">
				<ul class="pagination justify-content-center">
					{% if noticias.has_previous %}
						<li class="page-item ">
							<a class="page-link" href="?page={{ noticias.previous_page_number }}">&laquo;</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#" tabindex="-1">&laquo;</a>
						</li>
					{% endif %}

					{% for page in noticias.paginator.page_range %}
						<li class="page-item {% if noticias.number == page %}active{% endif %}">
							<a class="page-link" href="?page={{ page }}">{{ page }}</a>
						</li>
					{% endfor %}

					{% if noticias.has_next %}
						<li class="page-item ">
							<a class="page-link" href="?page={{ noticias.next_page_number }}">&raquo;</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#" tabindex="-1">&raquo;</a>
						</li>
					{% endif %}
				</ul>
			<nav aria-label="Page navigation">
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}