innovationLabs/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
]

innovationLabs/dashboard/urls.py
from django.urls import path
from .views import NoticiaListView, NoticiaCreate, NoticiaUpdate, NoticiaDelete 
from .views import EspecializacionListView, EspecializacionCreate, EspecializacionUpdate
from .views import EspecializacionDelete, RecursoCreate, RecursoListView, RecursoDelete, RecursoUpdate
from .views import ColaboradorListView, ColaboradorCreate, ColaboradorUpdate, ColaboradorDelete 
from . import views

app_name = "dashboard"

urlpatterns = [
	path('', views.dashboard, name="dashboard"),

	path('noticias-publicadas/', NoticiaListView.as_view(), name="publicadas"),
	path('nueva-noticia/', NoticiaCreate.as_view(), name="nueva"),
	path('editar-noticia/<int:pk>/', NoticiaUpdate.as_view(), name="editar"),
	path('borrar-noticia/<int:pk>/', NoticiaDelete.as_view(), name="borrar"),

	path('especializaciones-publicadas/', EspecializacionListView.as_view(), name="especializaciones-publicadas"),
	path('nueva-especializacion/', EspecializacionCreate.as_view(), name="nueva-especializacion"),
	path('editar-especializacion/<int:pk>/', EspecializacionUpdate.as_view(), name="editar-especializacion"),
	path('borrar-especializacion/<int:pk>/', EspecializacionDelete.as_view(), name="borrar-especializacion"),

	path('nuevo-recurso/', RecursoCreate.as_view(), name="nuevo-recurso"),
	path('recursos-publicados/', RecursoListView.as_view(), name="recursos-publicados"),
	path('borrar-recurso/<int:pk>/', RecursoDelete.as_view(), name="borrar-recurso"),
	path('editar-recurso/<int:pk>/', RecursoUpdate.as_view(), name="editar-recurso"),

	path('nuevo-colaborador/', ColaboradorCreate.as_view(), name="nuevo-colaborador"),
	path('colaboradores-publicados/', ColaboradorListView.as_view(), name="colaboradores-publicados"),
	path('borrar-colaborador/<int:pk>/', ColaboradorDelete.as_view(), name="borrar-colaborador"),
	path('editar-colaborador/<int:pk>/', ColaboradorUpdate.as_view(), name="editar-colaborador")

]

innovationLabs/especializacion/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.especializaciones, name="especializacion"),
	path('especializacion/<int:especializacion_id>/<slug:especializacion_slug>/', views.especializacion, name="especializacion"),
]

innovationLabs/innovationLabs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'core.views.page_not_found'

urlpatterns = [
	# paths del core
	path('', include('core.urls')),
    # paths de noticias
    path('noticias/', include('noticias.urls')),
    # paths de especializacion
    path('especializacion/', include('especializacion.urls')),
    # paths de normativa
    path('normativas/', include('normativa.urls')),
    # paths de laboratorios
    path('laboratorios/', include('laboratorios.urls')),
    # paths de recursos
    path('recursos/', include('recursos.urls')),
    # paths de colaboradores
    path('colaboradores/', include('colaboradores.urls')),
    # paths de login
    path('accounts/', include('django.contrib.auth.urls')),
    # paths de dashboard
    path('dashboard/', include('dashboard.urls')),
	# paths del admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovationLabs/especializacion/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from stdimage import StdImageField, validators
# from stdimage.validators import MinSizeValidator, MaxSizeValidator

class Especializacion(models.Model):
    laboratorio = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    nombre_laboratorio = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(verbose_name="titulo", max_length=200)
    content = RichTextField(verbose_name="contenido")
    # image = StdImageField(upload_to = "noticiasEspecializacion", verbose_name="imagen", blank=True, null=True, variations={'thumbnail': (960, 540)}, validators=[MinSizeValidator(960, 540)])
    image = StdImageField(upload_to = "noticiasEspecializacion", verbose_name="imagen", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Especialización"
        verbose_name_plural = "Especializaciones"
        ordering = ['created']

    def __str__(self):
        return self.title

innovationLabs/especializacion/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import Group, User
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Especializacion
from normativa.models import Normativa

def especializaciones(request):

	especializaciones = Especializacion.objects.all().order_by('-created')[:36]
	normativas = Normativa.objects.all().order_by('created')

	paginator = Paginator(especializaciones, 9)
	page = request.GET.get('page')

	try:
		especializaciones = paginator.page(page)
	except PageNotAnInteger:
		especializaciones = paginator.page(1)
	except EmptyPage:
		especializaciones = paginator.page(paginator.num_pages)

	return render(request, "especializacion/especializaciones.html", {'especializaciones': especializaciones, 'normativas':normativas})


def especializacion(request, especializacion_id, especializacion_slug):
	especializacion = get_object_or_404(Especializacion, id=especializacion_id)
	normativas = Normativa.objects.all().order_by('created')
	publicaciones_recientes = Especializacion.objects.exclude(id=especializacion_id).order_by('-id')[:4]

	try:
		querry_group=Group.objects.filter(user=especializacion.laboratorio_id)
	except:
		querry_group=None
	
	return render(request, "especializacion/especializacion.html", {
		'especializacion': especializacion,
		'publicaciones_recientes': publicaciones_recientes,
		'groups': querry_group, 
		'normativas':normativas
	})

innovationLabs/especializacion/templates/especializacion/especializacion.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <main class="col-lg-8">
      <div class="blog-post mt-2">
        <h2 class="blog-post-title">{{especializacion.title}}</h2>
        <p class="blog-post-meta">{{especializacion.created | date:"SHORT_DATE_FORMAT"}} por
        
        {% if especializacion.laboratorio %}
          - Redactado por
          <strong>{{especializacion.laboratorio.first_name}} {{especializacion.laboratorio.last_name}}</strong>
          {% for group in groups %}
            colaborador de <strong>{{group}}</strong></p>
          {% endfor %}
        {% endif %}

        {% if especializacion.image.url != None %}
          <img class="mt-3" src="{{especializacion.image.url}}" loading="lazy" width="100%" height="100%">
          <hr class="mt-5">
        {% endif %}
        {{especializacion.content|safe}}
      </div>

      <a type="button" class="btn btn-outline-primary float-left mt-4" href="{% url 'especializacion' %}" >
        <i class="fas fa-arrow-left"></i> Regresar
      </a>
    </main>

    <aside class="col-lg-4 mt-5">
      <h4 class="mt-5 mb-4">Publicaciones recientes</h4>
        <div>
        {% for publicacion in publicaciones_recientes %}
          <a href="{% url 'especializacion' publicacion.id publicacion.title|slugify %}">
            <div class="card border-primary mb-2 p-0">
              <div class="row no-gutters">
                <div class="col-6">
                  {% if publicacion.image.url != None %}
                    <img src="{{publicacion.image.url}}" class="img-fluid" alt="...">
                  {% endif %}
                </div>
                <div class="col-6">
                  <div class=" px-2">
                    <small style="color: black;">{{publicacion.title}}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
        {% endfor %}
      </div>
    </aside>
  </div>
</div>
{% endblock %}

innovationLabs/especializacion/templates/especializacion/especializacion_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}

{% load static %}

{% block content %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form action="" method="post">{% csrf_token %}
              <h3>¿Estás seguro de que quieres borrar la Especialización <strong>{{ object.title }}</strong>?</h3>
              <input class="btn btn-danger" type="submit" value="Sí, borrar la especialización"/>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

innovationLabs/especializacion/templates/especializacion/especializacion_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}
<br>
<div class="col-12">
  
  {% if 'ok' in request.GET %}
  <div class="alert alert-success" role="alert">
    Especialización actualizada correctamente
  </div>
  {% endif %}

  <form method="post" enctype="multipart/form-data">{% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="Guardar">
  </form>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

innovationLabs/especializacion/templates/especializacion/especializacion_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

<main role="main">
  <div class="container">

    <a class="btn btn-success float-right" href="{% url 'dashboard:nueva-especializacion' %}">
      <i class="fas fa-plus"></i> Nueva especialización
    </a>
    
    <br><br>

    {% for especializacion in especializacion_list %}
      <h4 class="mb-2">{{especializacion.title}}</h4>
      {% if especializacion.image.url != None %}
        <img src="{{especializacion.image.url}}" width="192" height="108" class="mb-2">
      {% endif %}
      <p>{{especializacion.content|striptags|safe|truncatechars:"300"}}</p>
      <a class="btn btn-warning btn-sm" href="{% url 'dashboard:editar-especializacion' especializacion.id %}">
        <i class="fas fa-edit"></i> Editar</a>
      <a class="btn btn-danger btn-sm" href="{% url 'dashboard:borrar-especializacion' especializacion.id %}">
        <i class="fas fa-trash"></i> Borrar</a>
      <hr>
    {% endfor %}
  </div>

  <!-- Menú de paginación -->
  {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&laquo;</a>
          </li>
        {% endif %}
        {% for i in paginator.page_range %}
          <li class="page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
</main>
{% endblock %}

innovationLabs/especializacion/templates/especializacion/especializaciones.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <div class="col-12">
      <div class="text-center mt-2">
        <h1 class="text-center">Especialización</h1>
        <hr class="pb-5">
      </div>
    </div>
  </div>

  <div class="row">
    {% for especializacion in especializaciones %}
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card text-dark border-primary mb-4">
          {% if especializacion.image.url != None %}
            <a href="{% url 'especializacion' especializacion.id especializacion.title|slugify %}">
              <img src="{{especializacion.image.url}}" loading="lazy" class="img-fluid" alt="...">
            </a>
          {% endif %}
          <div class="card-body">
            <a href="{% url 'especializacion' especializacion.id especializacion.title|slugify %}" class="card-title"
               style="color: black; font-weight: bold;">
                {{especializacion.title}}
            </a>
            <hr>
            <p class="card-text text-justify">{{especializacion.content|striptags|safe|truncatechars:"125"}}</p>
  					<p class="float-left">{{especializacion.created | date:"SHORT_DATE_FORMAT"}}</p>
            <a href="{% url 'especializacion' especializacion.id especializacion.title|slugify %}" class="float-right">Leer Más</a>
          </div>
        </div>
      </div>
    {% endfor %}
	</div>
		
  <div class="col-12">
    <!-- Menú de paginación -->
    {% if especializaciones.has_next or especializaciones.has_previous %}
    <br>
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if especializaciones.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ especializaciones.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&laquo;</a>
          </li>
        {% endif %}

        {% for page in especializaciones.paginator.page_range %}
          <li class="page-item {% if especializaciones.number == page %}active{% endif %}">
            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
          </li>
        {% endfor %}

        {% if especializaciones.has_next %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ especializaciones.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    <nav aria-label="Page navigation">
    {% endif %}
  </div>
</div>
{% endblock %}