innovationLabs/colaboradores/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.colaboradores, name="colaboradores"),
]

innovationLabs/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
]

innovationLabs/dashboard/urls.py
from django.urls import path
from .views import NoticiaListView, NoticiaCreate, NoticiaUpdate, NoticiaDelete 
from .views import EspecializacionListView, EspecializacionCreate, EspecializacionUpdate
from .views import EspecializacionDelete, RecursoCreate, RecursoListView, RecursoDelete, RecursoUpdate
from .views import ColaboradorListView, ColaboradorCreate, ColaboradorUpdate, ColaboradorDelete 
from . import views

app_name = "dashboard"

urlpatterns = [
	path('', views.dashboard, name="dashboard"),

	path('noticias-publicadas/', NoticiaListView.as_view(), name="publicadas"),
	path('nueva-noticia/', NoticiaCreate.as_view(), name="nueva"),
	path('editar-noticia/<int:pk>/', NoticiaUpdate.as_view(), name="editar"),
	path('borrar-noticia/<int:pk>/', NoticiaDelete.as_view(), name="borrar"),

	path('especializaciones-publicadas/', EspecializacionListView.as_view(), name="especializaciones-publicadas"),
	path('nueva-especializacion/', EspecializacionCreate.as_view(), name="nueva-especializacion"),
	path('editar-especializacion/<int:pk>/', EspecializacionUpdate.as_view(), name="editar-especializacion"),
	path('borrar-especializacion/<int:pk>/', EspecializacionDelete.as_view(), name="borrar-especializacion"),

	path('nuevo-recurso/', RecursoCreate.as_view(), name="nuevo-recurso"),
	path('recursos-publicados/', RecursoListView.as_view(), name="recursos-publicados"),
	path('borrar-recurso/<int:pk>/', RecursoDelete.as_view(), name="borrar-recurso"),
	path('editar-recurso/<int:pk>/', RecursoUpdate.as_view(), name="editar-recurso"),

	path('nuevo-colaborador/', ColaboradorCreate.as_view(), name="nuevo-colaborador"),
	path('colaboradores-publicados/', ColaboradorListView.as_view(), name="colaboradores-publicados"),
	path('borrar-colaborador/<int:pk>/', ColaboradorDelete.as_view(), name="borrar-colaborador"),
	path('editar-colaborador/<int:pk>/', ColaboradorUpdate.as_view(), name="editar-colaborador")

]

innovationLabs/innovationLabs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'core.views.page_not_found'

urlpatterns = [
	# paths del core
	path('', include('core.urls')),
    # paths de noticias
    path('noticias/', include('noticias.urls')),
    # paths de especializacion
    path('especializacion/', include('especializacion.urls')),
    # paths de normativa
    path('normativas/', include('normativa.urls')),
    # paths de laboratorios
    path('laboratorios/', include('laboratorios.urls')),
    # paths de recursos
    path('recursos/', include('recursos.urls')),
    # paths de colaboradores
    path('colaboradores/', include('colaboradores.urls')),
    # paths de login
    path('accounts/', include('django.contrib.auth.urls')),
    # paths de dashboard
    path('dashboard/', include('dashboard.urls')),
	# paths del admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovationLabs/colaboradores/models.py
from django.db import models
from stdimage import StdImageField, validators
from django.contrib.auth.models import User

class Colaborador(models.Model):
    laboratorio = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    nombre_laboratorio = models.CharField(max_length=200, blank=True, null=True)
    colaborador = models.CharField(verbose_name="colaborador", max_length=200)
    descripcion = models.CharField(verbose_name="descripcion", max_length=250, blank=True, null=True)
    sitioweb = models.CharField(verbose_name="sitioweb", max_length=250, blank=True, null=True)
    image = StdImageField(upload_to = "colaboradores", verbose_name="imagen", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")


    class Meta:
        verbose_name = "colaborador"
        verbose_name_plural = "colaboradores"
        ordering = ['created']

    def __str__(self):
        return self.title

innovationLabs/colaboradores/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Colaborador
from normativa.models import Normativa

def colaboradores(request):
	colaboradores = Colaborador.objects.all().order_by('-created')
	paginator = Paginator(colaboradores, 12)
	page = request.GET.get('page')

	normativas = Normativa.objects.all().order_by('created')

	try:
		colaboradores = paginator.page(page)
	except PageNotAnInteger:
		colaboradores = paginator.page(1)
	except EmptyPage:
		colaboradores = paginator.page(paginator.num_pages)
	return render(request, "colaboradores/colaboradores.html", {"colaboradores": colaboradores, 'normativas':normativas})

innovationLabs/colaboradores/templates/colaboradores/colaborador_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}

{% load static %}

{% block content %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form method="post">{% csrf_token %}
              <h3>¿Estás seguro de que quieres borrar el colaborador <strong>{{ object.title }}</strong>?</h3>
              <input class="btn btn-danger" type="submit" value="Sí, borrar el colaborador"/>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

innovationLabs/colaboradores/templates/colaboradores/colaborador_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}
<div>
  <br><br>
  <form method="post" enctype="multipart/form-data">{% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input class="btn btn-primary" type="submit" value="Guardar">
  </form>
</div>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

innovationLabs/colaboradores/templates/colaboradores/colaborador_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

<main role="main">
  <div class="container">

    <a class="btn btn-success float-right" href="{% url 'dashboard:nuevo-colaborador' %}">
      <i class="fas fa-plus"></i> Nuevo Colaborador
    </a>
    
    <br><br>

    {% for colaborador in colaborador_list %}
      <h4>{{colaborador.colaborador}}</h4>

      {% if colaborador.image.url != None %}
        <img src="{{colaborador.image.url}}" width="100" height="100" class="mb-2">
      {% endif %}

      {% if colaborador.descripcion != None %}
        <p>{{colaborador.descripcion|striptags|safe|truncatechars:"250"}}</p>
      {% endif %}

      {% if colaborador.sitioweb != None %}
        <p>{{colaborador.sitioweb}}</p>
      {% endif %}

      <a class="btn btn-warning btn-sm" href="{% url 'dashboard:editar-colaborador' colaborador.id %}">
        <i class="fas fa-edit"></i> Editar</a>
      <a class="btn btn-danger btn-sm" href="{% url 'dashboard:borrar-colaborador' colaborador.id %}">
        <i class="fas fa-trash"></i> Borrar</a>
      <hr>
    {% endfor %}
  </div>

  <!-- Menú de paginación -->
  {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&laquo;</a>
          </li>
        {% endif %}
        {% for i in paginator.page_range %}
          <li class="page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
</main>
{% endblock %}

innovationLabs/colaboradores/templates/colaboradores/colaborador_update_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}
  <div>
    <br>
    {% if 'ok' in request.GET %}
    <div class="alert alert-success" role="alert">
      Colaborador actualizado correctamente
    </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input class="btn btn-primary" type="submit" value="Actualizar colaborador">
    </form>
  </div>
  
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

innovationLabs/colaboradores/templates/colaboradores/colaboradores.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="text-center">
        <!-- <img src="{% static 'core/img/vector.png' %}" width="70%" height="70%" > -->
        <h1 class="text-center">Colaboradores</h1>
        <hr>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12"> 

      <div class="row">
        {% for colaborador in colaboradores %}
          <div class="col-md-6 col-sm-12">
            <div class="card bg-primary mb-4 border-primary" style="border-radius: 15px;">
              <div class="row no-gutters">
                <div class="col-md-4">
                  {% if colaborador.image %}
                    <img src="{{colaborador.image.url}}" class="card-img" width="100%" height="100%" style="border-radius: 15px;">
                  {% else %}
                    <img src="{% static 'core/img/no-image.jpg' %}" class="card-img" width="100%" height="100%" style="border-radius: 15px;">
                  {% endif %}
                </div>

                <div class="col-md-8 border-primary">
                  <div class="card-body text-white">
                    <h5 class="card-title">{{colaborador.colaborador}}</h5>
                    {% if colaborador.descripcion %}
                      <small>{{colaborador.descripcion}}</small>
                    {% endif %}
                    <br>
                    {% if colaborador.sitioweb %}
                      <br>
                      <small class="font-weight-bold">Sitio web: <a class="card-text text-white font-weight-normal" href="{{ colaborador.sitioweb }}" target="_blank">{{colaborador.sitioweb}}</a></small>
                      <br>
                    {% endif %}
                    <br>
                    {% if colaborador.laboratorio %}
                      <label class="p-1 etiqueta">{{ colaborador.nombre_laboratorio }}</label>
                      <!-- <p class="card-text">Colaborador de: <strong class="card-text">{{ colaborador.nombre_laboratorio }}</strong></p> -->
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <div class="col-12">
          <!-- Menú de paginación -->
        {% if colaboradores.has_next or colaboradores.has_previous %}
          <br>
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              {% if colaboradores.has_previous %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ colaboradores.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
              {% endif %}
    
              {% for page in colaboradores.paginator.page_range %}
                <li class="page-item {% if colaboradores.number == page %}active{% endif %}">
                  <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                </li>
              {% endfor %}
    
              {% if colaboradores.has_next %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ colaboradores.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          <nav aria-label="Page navigation">
          {% endif %}
        </div>

    </div>
  </div>

</div>

<br><br><br>

{% endblock %}