innovationLabs/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
]

innovationLabs/dashboard/urls.py
from django.urls import path
from .views import NoticiaListView, NoticiaCreate, NoticiaUpdate, NoticiaDelete 
from .views import EspecializacionListView, EspecializacionCreate, EspecializacionUpdate
from .views import EspecializacionDelete, RecursoCreate, RecursoListView, RecursoDelete, RecursoUpdate
from .views import ColaboradorListView, ColaboradorCreate, ColaboradorUpdate, ColaboradorDelete 
from . import views

app_name = "dashboard"

urlpatterns = [
	path('', views.dashboard, name="dashboard"),

	path('noticias-publicadas/', NoticiaListView.as_view(), name="publicadas"),
	path('nueva-noticia/', NoticiaCreate.as_view(), name="nueva"),
	path('editar-noticia/<int:pk>/', NoticiaUpdate.as_view(), name="editar"),
	path('borrar-noticia/<int:pk>/', NoticiaDelete.as_view(), name="borrar"),

	path('especializaciones-publicadas/', EspecializacionListView.as_view(), name="especializaciones-publicadas"),
	path('nueva-especializacion/', EspecializacionCreate.as_view(), name="nueva-especializacion"),
	path('editar-especializacion/<int:pk>/', EspecializacionUpdate.as_view(), name="editar-especializacion"),
	path('borrar-especializacion/<int:pk>/', EspecializacionDelete.as_view(), name="borrar-especializacion"),

	path('nuevo-recurso/', RecursoCreate.as_view(), name="nuevo-recurso"),
	path('recursos-publicados/', RecursoListView.as_view(), name="recursos-publicados"),
	path('borrar-recurso/<int:pk>/', RecursoDelete.as_view(), name="borrar-recurso"),
	path('editar-recurso/<int:pk>/', RecursoUpdate.as_view(), name="editar-recurso"),

	path('nuevo-colaborador/', ColaboradorCreate.as_view(), name="nuevo-colaborador"),
	path('colaboradores-publicados/', ColaboradorListView.as_view(), name="colaboradores-publicados"),
	path('borrar-colaborador/<int:pk>/', ColaboradorDelete.as_view(), name="borrar-colaborador"),
	path('editar-colaborador/<int:pk>/', ColaboradorUpdate.as_view(), name="editar-colaborador")

]

innovationLabs/innovationLabs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'core.views.page_not_found'

urlpatterns = [
	# paths del core
	path('', include('core.urls')),
    # paths de noticias
    path('noticias/', include('noticias.urls')),
    # paths de especializacion
    path('especializacion/', include('especializacion.urls')),
    # paths de normativa
    path('normativas/', include('normativa.urls')),
    # paths de laboratorios
    path('laboratorios/', include('laboratorios.urls')),
    # paths de recursos
    path('recursos/', include('recursos.urls')),
    # paths de colaboradores
    path('colaboradores/', include('colaboradores.urls')),
    # paths de login
    path('accounts/', include('django.contrib.auth.urls')),
    # paths de dashboard
    path('dashboard/', include('dashboard.urls')),
	# paths del admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovationLabs/dashboard/models.py
from django.db import models

#dfd

innovationLabs/dashboard/forms.py
from django.forms import ModelForm
from django import forms
from noticias.models import Noticia
from especializacion.models import Especializacion
from colaboradores.models import Colaborador
from recursos.models import Recurso
from django.forms.widgets import HiddenInput

class NoticiaForm(ModelForm):

    class Meta:
        model = Noticia
        fields = ['title', 'content', 'image', 'destacada']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control mb-2', 'placeholder':'Título de la Noticia'}),
            'image': forms.ClearableFileInput(attrs={'class':'mb-2'}),
            'destacada': forms.CheckboxInput,
        }

        labels = {
			'title':'Título', 
            'content': 'Contenido',
            'image': 'Imágen',
            'destacada': 'Destacada'
		}

class EspecializacionForm(ModelForm):

    class Meta:
        model = Especializacion
        fields = ['title', 'content', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control mb-2', 'placeholder':'Título de la Especialización'}),
            'image': forms.ClearableFileInput(attrs={'class':'mb-2'}),
        }

        labels = {
			'title':'Título', 
            'content': 'Contenido',
            'image': 'Imágen',
		}

class RecursoForm(ModelForm):

    class Meta:
        model = Recurso
        fields = ['title', 'archivo']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Nombre del Archivo'}),
            'archivo': forms.ClearableFileInput(attrs={'class':'mb-3'}),
        }

        labels = {
			'title':'Nombre', 
            'archivo': 'Archivo',
		}

class ColaboradorForm(ModelForm):

    class Meta:
        model = Colaborador
        fields = ['colaborador', 'descripcion', 'sitioweb', 'image']
        widgets = {
            'colaborador': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Nombre del Colaborador'}),
            'descripcion': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Descripción'}),
            'sitioweb': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Sitio Web'}),
            'image': forms.ClearableFileInput(attrs={'class':'mb-2'}),
        }

        labels = {
			'colaborador':'Colaborador', 
            'descripcion': 'Descripción',
            'sitioweb': 'Sitio Web',
            'image': 'Imágen',
		}

innovationLabs/dashboard/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from noticias.models import Noticia
from especializacion.models import Especializacion
from recursos.models import Recurso
from colaboradores.models import Colaborador
from .forms import NoticiaForm
from .forms import RecursoForm
from .forms import EspecializacionForm
from .forms import ColaboradorForm
from django import forms
from django.contrib.sessions.models import Session
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib import messages

def dashboard(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect("/")
		
	return render(request, "dashboard/dashboard_content.html")

# CRUD NOTICIAS

@method_decorator(login_required, name = 'dispatch')
class NoticiaListView(ListView):
	template_name = 'noticias/noticia_list.html'
	paginate_by = 4
	model = Noticia

	def get_queryset(self):
		return Noticia.objects.filter(laboratorio=self.request.user).order_by('-created')[:20]

@method_decorator(login_required, name = 'dispatch')
class NoticiaCreate(CreateView):
	template_name = 'noticias/noticia_form.html'
	form_class = NoticiaForm

	def form_valid(self, form):
		post = form.save(commit=False)
		post.laboratorio = self.request.user
		laboratorio = ""
		grupos_query = Group.objects.filter(user = self.request.user)
		for g in grupos_query:
			laboratorio = g.name
		post.nombre_laboratorio = laboratorio
		post.save()
		messages.success(self.request, 'Noticia creada correctamente')
		return HttpResponseRedirect(reverse('dashboard:publicadas'))

@method_decorator(login_required, name = 'dispatch')
class NoticiaUpdate(UpdateView):
	model = Noticia
	fields = ['title', 'content', 'image', 'destacada']

	def get_success_url(self):
		return reverse_lazy('dashboard:editar', args=[self.object.id]) + '?ok'

@method_decorator(login_required, name = 'dispatch')
class NoticiaDelete(DeleteView):
	model = Noticia

	def get_success_url(self):
		messages.success(self.request, 'Noticia eliminada correctamente')
		return reverse_lazy('dashboard:dashboard')

# CRUD ESPECIALIZACION

@method_decorator(login_required, name = 'dispatch')
class EspecializacionListView(ListView):
	template_name = 'especializacion/especializacion_list.html'
	paginate_by = 4
	model = Especializacion

	def get_queryset(self):
		return Especializacion.objects.filter(laboratorio=self.request.user).order_by('-created')[:50]

@method_decorator(login_required, name = 'dispatch')
class EspecializacionCreate(CreateView):
	template_name = 'especializacion/especializacion_form.html'
	form_class = EspecializacionForm

	def form_valid(self, form):
		post = form.save(commit=False)
		post.laboratorio = self.request.user
		laboratorio = ""
		grupos_query = Group.objects.filter(user = self.request.user)
		for g in grupos_query:
			laboratorio = g.name
		post.nombre_laboratorio = laboratorio
		post.save()
		messages.success(self.request, 'Especializacion creada correctamente')
		return HttpResponseRedirect(reverse('dashboard:especializaciones-publicadas'))

@method_decorator(login_required, name = 'dispatch')
class EspecializacionUpdate(UpdateView):
	model = Especializacion
	fields = ['title', 'content', 'image']
	
	def get_success_url(self):
		return reverse_lazy('dashboard:editar-especializacion', args=[self.object.id]) + '?ok'

@method_decorator(login_required, name = 'dispatch')
class EspecializacionDelete(DeleteView):
	model = Especializacion

	def get_success_url(self):
		messages.success(self.request, 'Especializacion eliminada correctamente')
		return reverse_lazy('dashboard:dashboard')

# CRUD RECURSOS

@method_decorator(login_required, name = 'dispatch')
class RecursoListView(ListView):
	template_name = 'noticias/recurso_list.html'
	model = Recurso
	paginate_by = 5
	
	def get_queryset(self):
		return Recurso.objects.filter(laboratorio=self.request.user).order_by('-created')[:20]

@method_decorator(login_required, name = 'dispatch')
class RecursoCreate(CreateView):
	template_name = 'recursos/recurso_form.html'
	form_class = RecursoForm

	def form_valid(self, form):
		post = form.save(commit=False)
		post.laboratorio = self.request.user
		laboratorio = ""
		grupos_query = Group.objects.filter(user = self.request.user)
		for g in grupos_query:
			laboratorio = g.name
		post.nombre_laboratorio = laboratorio
		post.save()
		messages.success(self.request, 'Recurso subido correctamente')
		return HttpResponseRedirect(reverse('dashboard:recursos-publicados'))

@method_decorator(login_required, name = 'dispatch')
class RecursoUpdate(UpdateView):
	model = Recurso
	fields = ['title', 'archivo']
	widgets = {
		'title': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Nombre del Archivo'}),
		'archivo': forms.ClearableFileInput(attrs={'class':'mb-3'}),
	}
	template_name_suffix = '_update_form'

	def get_success_url(self):
		return reverse_lazy('dashboard:editar-recurso', args=[self.object.id]) + '?ok'

@method_decorator(login_required, name = 'dispatch')
class RecursoDelete(DeleteView):
	model = Recurso

	def get_success_url(self):
		messages.success(self.request, 'Recurso eliminado correctamente')
		return reverse_lazy('dashboard:recursos-publicados')

# CRUD COLABORADORES

@method_decorator(login_required, name = 'dispatch')
class ColaboradorListView(ListView):
	template_name = 'colaboradores/colaborador_list.html'
	paginate_by = 4
	model = Colaborador

	def get_queryset(self):
		return Colaborador.objects.filter(laboratorio=self.request.user).order_by('-created')[:20]

@method_decorator(login_required, name = 'dispatch')
class ColaboradorCreate(CreateView):
	template_name = 'colaboradores/colaborador_form.html'
	form_class = ColaboradorForm

	def form_valid(self, form):
		post = form.save(commit=False)
		post.laboratorio = self.request.user
		laboratorio = ""
		grupos_query = Group.objects.filter(user = self.request.user)
		for g in grupos_query:
			laboratorio = g.name
		post.nombre_laboratorio = laboratorio
		post.save()
		messages.success(self.request, 'Colaborador creado correctamente')
		return HttpResponseRedirect(reverse('dashboard:colaboradores-publicados'))

@method_decorator(login_required, name = 'dispatch')
class ColaboradorUpdate(UpdateView):
	model = Colaborador
	fields = ['colaborador', 'descripcion', 'sitioweb', 'image']
	widgets = {
            'colaborador': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Nombre del Colaborador'}),
            'descripcion': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Descripción'}),
            'sitioweb': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder':'Sitio Web'}),
            'image': forms.ClearableFileInput(attrs={'class':'mb-2'}),
        }
	labels = {
			'colaborador':'Colaborador', 
            'descripcion': 'Descripción',
            'sitioweb': 'Sitio Web',
            'image': 'Imágen',
		}
	template_name_suffix = '_update_form'
	
	def get_success_url(self):
		return reverse_lazy('dashboard:editar-colaborador', args=[self.object.id]) + '?ok'

@method_decorator(login_required, name = 'dispatch')
class ColaboradorDelete(DeleteView):
	model = Colaborador

	def get_success_url(self):
		messages.success(self.request, 'Colaborador eliminado correctamente')
		return reverse_lazy('dashboard:dashboard')

innovationLabs/dashboard/templates/dashboard/dashboard_base.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Panel de Administración</title>

    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'core/img/favicon.ico' %}"/>
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'core/css/all.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static '/core/css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <h1 class="navbar-brand col-sm-3 col-md-2 mr-0">
        Panel de Administración
      </h1>

      <div class="dropdown">
        <a class="btn btn-danger dropdown-toggle" href="#" role="button" id="dropdownMenuLink" 
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="far fa-user text-center"></i> Salir / Cerrar Sesión
        </a>
          
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="{% url 'home'%}">Volver al Sitio</a>
          <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar de Contraseña</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
        </div>
      </div>

    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">

              <li class="nav-item">
                <a class="nav-link {% if request.path == '/dashboard/' %} active {% endif %}" href="{% url 'dashboard:dashboard' %}">
                  <i class="fas fa-home"></i> Inicio
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% if request.path == '/dashboard/noticias-publicadas/' %} active {% endif %}" href="{% url 'dashboard:publicadas' %}">
                  <i class="fas fa-newspaper"></i> Noticias 
                </a>
              </li>

              <li class="nav-item">
                <a  href="{% url 'dashboard:especializaciones-publicadas' %}" class="nav-link 
                  {% if request.path == '/dashboard/especializaciones-publicadas/' %} 
                    active 
                  {% endif %}">
                  <i class="fas fa-globe"></i> Especialización
                </a>
              </li>

              <li class="nav-item">
                <a  href="{% url 'dashboard:colaboradores-publicados' %}" class="nav-link 
                  {% if request.path == '/dashboard/colaboradores-publicados/' %} 
                    active 
                  {% endif %}">
                  <i class="fas fa-users"></i> Colaboradores
                </a>
              </li>

              <li class="nav-item">
                <a href="{% url 'dashboard:recursos-publicados'%}" class="nav-link 
                  {% if '/recursos-publicados/' in request.path %} 
                    active 
                  {% endif %}">
                  <i class="fas fa-book"></i> Recursos 
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'home'%}">
                  <i class="fas fa-arrow-left"></i> Regresar al sitio
                </a>
              </li>
            </ul>
          </div>  
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        {% if messages %}
          {% for message in messages %}
            <br>
            <div class="alert {% if message.tags %}
                  alert-{{ message.tags }}
                  {% endif %}" role="alert">{{ message }} 
            </div>
          {% endfor %}
        {% endif %}
          {% block content %}{% endblock %}
        </main>
        
  </div>
</div>

  <script src="{% static 'core/js/jquery-3.3.1.slim.min.js' %}" integrity="" crossorigin="anonymous"></script>

  <script src="{% static 'core/js/bootstrap.min.js' %}" integrity="" crossorigin="anonymous"></script>
</html>

innovationLabs/dashboard/templates/dashboard/dashboard_content.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}
<div class="row">

  <div class="col-12 d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Bienvenido {{ user.first_name }} {{ user.last_name }}</h1>
    <br>
  </div>
    
  <div class="col-lg-6 col-sm-12">
    <h4>Noticias</h4>

    <a type="button" class="btn btn-success" href="{% url 'dashboard:nueva' %}">
      <i class="fas fa-plus"></i> Crear una Noticia
    </a>

    <a type="button" class="btn btn-primary" href="{% url 'dashboard:publicadas' %}">
      <i class="fas fa-newspaper"></i> Ver lista de Noticias
    </a>

    <hr><br>

  </div>

  <div class="col-lg-6 col-sm-12">
    <h4>Especialización</h4>

    <a type="button" class="btn btn-success" href="{% url 'dashboard:nueva-especializacion' %}">
      <i class="fas fa-plus"></i> Crear Especialización
    </a>

    <a type="button" class="btn btn-primary" href="{% url 'dashboard:especializaciones-publicadas' %}">
      <i class="fas fa-globe"></i> Ver lista de Especialización
    </a>

    <hr><br>

  </div>

  <div class="col-lg-6 col-sm-12">

    <h4>Recursos</h4>

    <a type="button" class="btn btn-success" href="{% url 'dashboard:nuevo-recurso'%}">
      <i class="fas fa-plus"></i> Subir recurso
    </a>
    <a type="button" class="btn btn-primary" href="{% url 'dashboard:recursos-publicados'%}">
      <i class="fas fa-book"></i> Ver lista de Recursos
    </a>

    <hr><br>

  </div>  

  <div class="col-lg-6 col-sm-12">

    <h4>Colaboradores</h4>

    <a type="button" class="btn btn-success" href="{% url 'dashboard:nuevo-colaborador'%}">
      <i class="fas fa-plus"></i> Nuevo Colaborador
    </a>
    <a type="button" class="btn btn-primary" href="{% url 'dashboard:colaboradores-publicados'%}">
      <i class="fas fa-users"></i> Ver lista de Colaboradores
    </a>

    <hr><br>

  </div>  

  <div class="col-12">
    <a type="button" class="btn btn-warning" href="{% url 'home'%}">
      <i class="fas fa-arrow-left"></i> Regresar al Sitio
    </a>
  </div>

</div>
{% endblock %}

innovationLabs/dashboard/templates/dashboard/dashboard_simple.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Dashboard</title>

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'core/css/styles.css' %}" integrity="" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
    <!-- Custom styles for this template -->
    <link href="{% static 'core/css/login.css' %}" rel="stylesheet">

  </head>
  <body>

    {% block content %}{% endblock %}

    <script src="{% static 'core/js/jquery-3.3.1.slim.min.js' %}" integrity="" crossorigin="anonymous"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}" integrity="" crossorigin="anonymous"></script>
  </body>
</html>